###  Limit order Request Bid
POST http://localhost:3000/order

{
  "bid": true,
  "size": 20,
  "price": 9000.0,
  "type": "LIMIT",
  "market": "ETH"
   
}
###  Limit order Request Bid 2
POST http://localhost:3000/order

{
  "bid": true,
  "size": 20,
  "price": 90000.0,
  "type": "LIMIT",
  "market": "ETH"
   
}

###  Limit order Request Ask
POST http://localhost:3000/order

{
  "bid": false,
  "size": 20,
  "price": 9000.0,
  "type": "LIMIT",
  "market": "ETH"
   
}

### Market order Request 
POST http://localhost:3000/order

{
  "bid": false,
  "size": 10,
  "type": "MARKET",
  "market": "ETH"
   
}

###  Correct GET Request
GET http://localhost:3000/book/ETH

{
  
}

### Cancel Order
DELETE  http://localhost:3000/order/4086162

{
   
}

